name: AI CI Assist

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'jjb/**/*.yaml'

jobs:
  ai-assist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run JJB validation
        run: |
          python analyzer/jjblint.py

      - name: Run AI suggestions
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Running AI assist..."
          python analyzer/suggest_improvements.py
